retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/elt_service_account.json
    project: ancient-script-401013
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US